### PR TITLE
Changes make the sap_hana_scaleout example consistent with the other …

### PR DESCRIPTION
**Pull request by sjswerdlow**
Changes make the sap_hana_scaleout example consistent with the other examples also updating the path in the readmes to correctly link.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@sjswerdlow
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by sjswerdlow** [comment]
Awais, exactly how do we actually release these?

**Comment by comment-bot-dev** [comment]
@sjswerdlow
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@sjswerdlow
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by g-awmalik — APPROVED** [review]

**Comment by comment-bot-dev** [comment]
@sjswerdlow
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
