### PR TITLE
Fix: Wrong disk sizes for HANA VMs issue #18

### PR DESCRIPTION
**Pull request by emmanuelsomeox**
currently SSD and standard disk have the same (SSD).
Set size of the standard disk based on the size calculated by sap_hana.py

fix: issue #18

### CODE REVIEW

**Review by morgante — CHANGES_REQUESTED** [review]
Please run `terraform fmt` to make sure linters pass. Thanks!

**Comment by emmanuelsomeox** [comment]
Hello,
I mistakenly put my PR for the management of Shared VPCs in this PR.
The goal of this PR is to add the management of deployment in a Shared VPC.
A new optional variable host_project_id allows the deployment in a Shared VPC.

**Comment by morgante** [comment]
Please make sure the examples/tests work correctly (or pull out the shared VPC commit, since that's what broke the tests).

**Comment by emmanuelsomeox** [comment]
Sorry for the issues, I am new with these tools. 
I close this PR, order my developement and recreate a new PR.

**Pull request closed without merging**
